In [3]:
import numpy as np
import tensorflow as tf
from analysis_functions import Analysis

2023-06-05 13:55:21.167008: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-06-05 13:55:21.167057: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [4]:
uqc_2qubits_2layers_path = "../../results/overparametrization/2_qubits_2layer"
skolik_path = "../../results/overparametrization/skolik"

skolik = Analysis(skolik_path)
uqc_2qubits_2layers = Analysis(uqc_2qubits_2layers_path)

In [5]:
uqc_2qubits_2layers_weights = uqc_2qubits_2layers.get_final_weights()
skolik_weights = skolik.get_final_weights()

In [8]:
weights = uqc_2qubits_2layers_weights[0][:-1]

In [9]:
weights

[array([[1.8468791 , 1.1475711 , 1.9329507 , 0.97739553]], dtype=float32),
 array([[[-1.0944426 ,  0.05319272,  0.0381873 , -0.44517463],
         [-0.73402774, -0.05689103,  0.8435067 ,  0.374379  ]],
 
        [[-0.01729522,  0.53940433, -0.13945937,  1.7733059 ],
         [-0.07697394,  0.16660424,  0.21878794,  0.71627206]]],
       dtype=float32),
 array([[ 0.04547372,  0.06625698],
        [ 0.05631084, -0.09248722]], dtype=float32)]

In [11]:
combined_array = np.concatenate([lista.flatten() for lista in weights], axis=0)

In [110]:
combined_array = np.concatenate((weights[0].flatten(), weights[1].flatten(), weights[2].flatten()), axis=0)

In [12]:
combined_array

array([ 1.8468791 ,  1.1475711 ,  1.9329507 ,  0.97739553, -1.0944426 ,
        0.05319272,  0.0381873 , -0.44517463, -0.73402774, -0.05689103,
        0.8435067 ,  0.374379  , -0.01729522,  0.53940433, -0.13945937,
        1.7733059 , -0.07697394,  0.16660424,  0.21878794,  0.71627206,
        0.04547372,  0.06625698,  0.05631084, -0.09248722], dtype=float32)