In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pickle
import os

In [3]:
# Load the Data

gs_exp_non_path = "../../results/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper"
pickle_files = [f for f in os.listdir(gs_exp_non_path) if f.endswith(".pkl")]
gs_exp_non_agents = []

for pickle_file in pickle_files:
    with open(os.path.join(gs_exp_non_path, pickle_file), 'rb') as f:
        gs_exp_non_agents.append(pickle.load(f))
        # Do something with the agent data

In [4]:
gs_exp_non_agents[0]["weights"]

[array([[0.93203306, 2.5629804 , 1.6217475 , 2.728239  , 3.1276445 ]],
       dtype=float32),
 array([[ 0.26444513,  0.7693851 , -0.8167833 , -1.7268474 ],
        [-0.00549886,  0.5820641 , -1.1452103 ,  0.10333122],
        [-1.2968433 ,  0.13369344,  0.23310113,  1.8201323 ],
        [-1.3384502 , -2.8702576 ,  1.5164281 ,  0.52828425],
        [-0.6024033 ,  3.08327   , -1.126494  , -1.7457869 ]],
       dtype=float32),
 array([-0.75047517, -0.27597174,  2.7247653 , -1.8157327 ,  2.5507638 ],
       dtype=float32),
 array([[1.]], dtype=float32)]

In [ ]:
# Load the Data

#python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py
#python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py
#python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py
#python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/globalexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py
#python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py
#python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py
#python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py
#python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/globalskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py
#python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py
#python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_non_optimal_hyper.py
#python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py
#python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/localexpectation_outscaling/lastZ_obs/skolik_optimal_hyper.py
#python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py
#python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py & python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_non_optimal_hyper.py
#python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py
#python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py & python main.py configs/continuous/uqc/localskolik_outscaling/lastZ_obs/skolik_optimal_hyper.py